pretrained_model_path: "./checkpoints/stable-diffusion-v1-5"
pretrained_clip_path: "./checkpoints/clip-vit-base-patch32"
pretrained_unet_path: "./checkpoints/v3.2/unet_stage_1.ckpt"
pretrained_poseguider_path: "./checkpoints/v3.2/poseguider_stage_1.ckpt"
pretrained_referencenet_path: "./checkpoints/v3.2/referencenet_stage_1.ckpt"

savename: null

fusion_blocks: "full"


seed:           [42]
steps:          25
guidance_scale: 7.5
# guidance_scale: 0

source_image:
  - "/home/ubuntu/data/ubc_fashion/test/A1-Lv00GAzS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test/A191LVe3AzS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test/A1xphfMiftS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test/91tZgBKfXRS.mp4"
video_path:
  - "/home/ubuntu/data/ubc_fashion/test_dwpose/A1-Lv00GAzS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test_dwpose/A191LVe3AzS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test_dwpose/A1xphfMiftS.mp4"
  - "/home/ubuntu/data/ubc_fashion/test_dwpose/91tZgBKfXRS.mp4"

inference_config: "configs/inference/inference.yaml"
size: 768
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

