pretrained_model_path: "./checkpoints/stable-diffusion-v1-5"
pretrained_clip_path: "./checkpoints/clip-vit-base-patch32"
pretrained_unet_path: "./checkpoints/v3.3_nano/unet_stage_1.ckpt"
pretrained_poseguider_path: "./checkpoints/v3.3_nano/poseguider_stage_1.ckpt"
pretrained_referencenet_path: "./checkpoints/v3.3_nano/referencenet_stage_1.ckpt"

savename: null

fusion_blocks: "full"


seed:           [42]
steps:          25
guidance_scale: 7.5
# guidance_scale: 0

source_image:
  - "/home/ubuntu/data/ubc_fashion/train/A1cofEJXx3S.mp4"
video_path:
  - "/home/ubuntu/data/ubc_fashion/train_dwpose/A1cofEJXx3S.mp4"

inference_config: "configs/inference/inference.yaml"
size: 768
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

