image_finetune: true
name: my_train_stage_1
use_wandb: true
launcher: pytorch
output_dir: outputs/my_train_stage_1-2023-12-12T16-19-15
pretrained_model_path: checkpoints/stable-diffusion-v1-5
clip_model_path: checkpoints/clip-vit-base-patch32
description: '### train info: train stage 1: image pretrain ###'
fusion_blocks: full
poseguider_checkpoint_path: ''
referencenet_checkpoint_path: ''
train_data:
  csv_path: /home/ubuntu/code/AnimateAnyone-unofficial/data/TikTok_info.csv
  video_folder: /home/ubuntu/data/animate-anyone/TikTok_dataset
  sample_size: 256
  sample_stride: 4
  sample_n_frames: 16
  clip_model_path: checkpoints/clip-vit-base-patch32
validation_data:
  prompts:
  - Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and
    shadow deep canyons.
  - A drone view of celebration with Christma tree and fireworks, starry sky - background.
  - Robot dancing in times square.
  - Pacific coast, carmel by the sea ocean and waves.
  num_inference_steps: 25
  guidance_scale: 8.0
cfg_random_null_text: true
cfg_random_null_text_ratio: 0.1
unet_checkpoint_path: ''
unet_additional_kwargs: {}
ema_decay: 0.9999
noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: scaled_linear
  steps_offset: 1
  clip_sample: false
max_train_epoch: -1
max_train_steps: 30000
validation_steps: 5000
validation_steps_tuple:
- 2
- 50
learning_rate: 0.0001
scale_lr: false
lr_warmup_steps: 0
lr_scheduler: constant
trainable_modules:
- .
num_workers: 0
train_batch_size: 1
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
gradient_accumulation_steps: 16
gradient_checkpointing: false
checkpointing_epochs: -1
checkpointing_steps: 10000
mixed_precision_training: true
enable_xformers_memory_efficient_attention: true
global_seed: 42
is_debug: false
local_rank: 0
global_rank: 0
num_processes: 1
is_main_process: true
seed: 42
folder_name: my_train_stage_1-2023-12-12T16-19-15
