image_finetune: true

output_dir: "outputs"
pretrained_model_path: "checkpoints/stable-diffusion-v1-5"
clip_model_path: "checkpoints/clip-vit-base-patch32"
poseguider_checkpoint_path: "outputs.bak/train_stage_1_v4-2023-12-15T20-15-25/checkpoints/checkpoint.ckpt"
referencenet_checkpoint_path: "outputs.bak/train_stage_1_v4-2023-12-15T20-15-25/checkpoints/checkpoint.ckpt"

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

description: "### Train info: train stage 1: image pretrain ###"

train_data:
  csv_path:     "/home/ubuntu/code/AnimateAnyone-unofficial/data/TikTok_info.csv"
  video_folder: "/home/ubuntu/data/animate-anyone/TikTok_dataset/"
  sample_size:  512
  sample_stride: 4
  sample_n_frames: 36
  clip_model_path: "checkpoints/clip-vit-base-patch32"

validation_data:
  prompts:
    - "girl dancing in a room"
    - "girl dancing in a forest"
    - "boy dancing in a room"
    - "boy dancing in a forest"
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: ""

fusion_blocks: "full"

learning_rate:    1.e-6
train_batch_size: 16

max_train_epoch:      -1
max_train_steps:      5000
checkpointing_epochs: -1
checkpointing_steps:  500
gradient_accumulation_steps: 16


validation_steps:       500
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True

is_debug: False
snr_gamma: 5.0