image_finetune: false

output_dir: "outputs/"
folder_name: "w4.1"
pretrained_model_path: "./checkpoints/stable-diffusion-v1-5"
clip_model_path: "./checkpoints/clip-vit-base-patch32"
poseguider_checkpoint_path: "./checkpoints/v4.1/poseguider_stage_1.ckpt"
referencenet_checkpoint_path: "./checkpoints/v4.1/referencenet_stage_1.ckpt"
pretrained_unet_path: "./outputs/w4.1/checkpoints/"
unet_checkpoint_path: ""
specific_motion_unet_model: "checkpoint-global_step-29400.ckpt"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true


noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

description: "train stage 2: video motion train"

train_data:
  csv_path:     "./data/UBC_train_info.csv"
  video_folder: "/home/ubuntu/data/ubc_fashion/"
  sample_size:  768 # for 40G 256
  sample_stride: 4
  sample_n_frames: 8
  clip_model_path: "./checkpoints/clip-vit-base-patch32"

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 25
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."

fusion_blocks: "full"
learning_rate:    1.e-5
train_batch_size: 1

max_train_epoch:      -1
max_train_steps:      30000
checkpointing_epochs: -1
checkpointing_steps:  600
gradient_accumulation_steps: 16


validation_steps:       5000
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: false

is_debug: False

inference_config:
  reference_image_path: '/home/ubuntu/data/ubc_fashion/source_image/A1-Lv00GAzS.png'
  motion_sequence: '/home/ubuntu/data/ubc_fashion/driving/dwpose/A1-Lv00GAzS.mp4'
  config: "configs/prompts/v4/w4.1.yaml"
  specific_motion_unet_model: "checkpoint-global_step-29400.ckpt"
  pretrained_motion_unet_path: "./outputs/w4.1/checkpoints/"